[project]
name = "economyatlas"
version = "0.1.0"
description = "Interactive map with economic and historical data"
authors = [
    {name = "kosinus2000",email = "hubert.kosiorowski1@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "sqlalchemy (>=2.0.52,<3.0.0)",
    "psycopg[binary] (>=3.3.4,<4.0.0)",
    "python-dotenv (>=1.2.3,<2.0.0)",
    "load-dotenv (>=0.1.0,<0.2.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
