CREATE TABLE voivodeship
(
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    area FLOAT,
    population INTEGER,
    pkb NUMERIC(15, 2)
);

CREATE TABLE powiat
(
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
)